version: "3"
services:
  db:
    container_name: mysqlDB
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3307"
  apache:
    container_name: apache
    build: ./apache
    restart: always
    command: "/bin/sh -c 'apt-get update && 
      pecl uninstall redis &&
      pecl install -f redis &&
      docker-php-ext-enable redis &&
      docker-php-ext-install mysqli && 
      exec apache2-foreground'"
    volumes:
      - ./apache/pages:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/pages/static/uploads:/var/www/uploads/
    ports:
      - "8081:80"
    links:
      - db
      - nginx
      - redis
  nginx:
    container_name: nginx
    image: "nginx:latest"
    restart: always
    volumes:
      - ./nginx/pages:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  redis:
    image: "redis:alpine"