version: "3"
services:
  db:
    container_name: mysqlDB
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3307"
  apache:
    container_name: apache
    build: apache
    volumes:
      - ./apache/pages:/var/www/html/
      - ./apache/pages/static:/var/www/uploads/
    restart: always
    ports:
      - "8081:80"
    links:
      - db
      - nginx
      - redis
  nginx:
    container_name: nginx
    image: "nginx:latest"
    restart: always
    volumes:
      - ./nginx/pages:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  redis:
    image: "redis:alpine"